### ISSUE TITLE
File save/download file type issue

### ISSUE THREAD

**Issue by marcj303** [playasoft/weightlifter#81]
Some judges had a problem with file downloads in the last cycle. The filetype wasn't being saved or downloaded correctly, so users could open the files without guessing a file type locally. I don't know if this was with a specific OS or browser. Lets check the 2017 files and see what was happening.

**Comment by itsrachelfish** [comment]
I actually figured this out while working on the volunteer database and fixed the code in both projects a few months ago: https://github.com/playasoft/weightlifter/commit/c4c759af206130c97b8a80c74c125a89aac26eff

Basically, the old regex was stripping out any capital letters from files, so if a file was named "IMG_0223.JPG" it would be saved as "IMG_0223."
